In [2]:
import pandas as pd

# Loading the dataset
df = pd.read_csv('NetflixClustering_DB.csv')

In [ ]:
# Inspecting the first 5 rows to see the structure
print("--- Dataset Head ---")
print(df.head())

--- Dataset Head ---
  show_id     type  title           director  \
0      s1  TV Show     3%                NaN
1      s2    Movie   7:19  Jorge Michel Grau
2      s3    Movie  23:59       Gilbert Chan
3      s4    Movie      9        Shane Acker
4      s5    Movie     21     Robert Luketic

                                                cast        country  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...         Brazil
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...         Mexico
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...      Singapore
3  Elijah Wood, John C. Reilly, Jennifer Connelly...  United States
4  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...  United States

          date_added  release_year rating   duration  \
0    August 14, 2020          2020  TV-MA  4 Seasons
1  December 23, 2016          2016  TV-MA     93 min
2  December 20, 2018          2011      R     78 min
3  November 16, 2017          2009  PG-13     80 min
4    January 1, 2020          2008  PG-13    123 min

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...
1                       Dramas, International Movies
2                Horror Movies, International Movies
3  Action & Adventure, Independent Movies, Sci-Fi...
4                                             Dramas

                                         description
0  In a future where the elite inhabit an island ...
1  After a devastating earthquake hits Mexico Cit...
2  When an army recruit is found dead, his fellow...
3  In a postapocalyptic world, rag-doll robots hi...
4  A brilliant group of students become card-coun...

In [ ]:
#Last 5 rows
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [ ]:
# Checking the summary of the dataframe - columns, non-null counts and data types.
print("\n--- Data Information ---")
print(df.info())

--- Data Information ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB
None

In [5]:
df.describe(include="O")

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,7787,7787,7787,5398,7069,7280,7777,7780,7787,7787,7787
unique,7787,2,7787,4049,6831,681,1565,14,216,492,7769
top,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,"Raúl Campos, Jan Suter",David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,Documentaries,Multiple women report their husbands as missin...
freq,1,5377,1,18,18,2555,118,2863,1608,334,3

In [ ]:
#Random data from dataset
df.sample(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
172,s173,Movie,A Flying Jatt,Remo D'Souza,"Tiger Shroff, Jacqueline Fernandez, Nathan Jon...",India,"November 15, 2017",2016,TV-14,142 min,"Action & Adventure, International Movies, Sci-...",A timid man gets unexpected superpowers while ...
4129,s4130,Movie,Misfit,Erwin van den Eshof,"Djamila, Niek Roozen, Bente Fokkens, Jolijn He...",Netherlands,"August 3, 2019",2017,TV-14,81 min,"Children & Family Movies, Comedies, Internatio...","After living in America for years, a teenage g..."
7730,s7731,TV Show,You vs. Wild,NaN,Bear Grylls,United States,"April 10, 2019",2019,TV-PG,1 Season,"Kids' TV, Reality TV, Science & Nature TV","In this interactive series, you'll make key de..."
2343,s2344,Movie,Game Over (Tamil Version),Ashwin Saravanan,"Taapsee Pannu, Vinodhini, Parvathi T, Ramya Su...","India, Turkey","August 21, 2019",2019,TV-MA,98 min,"Horror Movies, International Movies, Thrillers","As a series of murders hit close to home, a vi..."
8,s9,Movie,706,Shravan Kumar,"Divya Dutta, Atul Kulkarni, Mohan Agashe, Anup...",India,"April 1, 2019",2019,TV-14,118 min,"Horror Movies, International Movies","When a doctor goes missing, his psychiatrist w..."
5852,s5853,Movie,Strong Island,Yance Ford,NaN,"United States, Denmark","September 15, 2017",2017,TV-MA,108 min,Documentaries,"The forces of family, grief and racial injusti..."
7025,s7026,TV Show,The Yard,NaN,"Demet Evgar, Ceren Moray, Nursel Köse, Kenan E...",Turkey,"November 15, 2019",2019,TV-MA,2 Seasons,"Crime TV Shows, International TV Shows, TV Dramas","After a fateful domestic clash, a devoted moth..."
7394,s7395,Movie,Vaya,Akin Omotoso,"Mncedisi Shabangu, Sihle Xaba, Sibusiso Msiman...",South Africa,"November 1, 2018",2016,TV-MA,106 min,"Dramas, Independent Movies, International Movies",Three youths from rural South Africa set out f...
503,s504,Movie,Anchor Baby,Lonzo Nzekwe,"Omoni Oboli, Sam Sarpong, Terri Oliver, Colin ...","Canada, Nigeria","May 20, 2020",2010,TV-MA,97 min,"Dramas, International Movies",A Nigerian couple living in the U.S. face agon...
2839,s2840,Movie,How the Grinch Stole Christmas,Ron Howard,"Jim Carrey, Taylor Momsen, Jeffrey Tambor, Chr...",United States,"June 1, 2017",2000,PG,105 min,"Children & Family Movies, Comedies",The Grinch decides to rob Whoville of Christma...

In [ ]:
# Identifying number of missing values exist per column
print("\n--- Missing Values Count ---")
print(df.isnull().sum())
#df.isna().sum() - other way to find number of null values.

--- Missing Values Count ---
show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

In [ ]:
# Checking for duplicate records
print("\n--- Duplicate Rows ---")
print(f"Number of duplicate entries: {df.duplicated().sum()}")

--- Duplicate Rows ---
Number of duplicate entries: 0

In [ ]:
#Top 5 Directors 
df["director"].value_counts().head(5)

director
Raúl Campos, Jan Suter    18
Marcus Raboy              16
Jay Karas                 14
Cathy Garcia-Molina       13
Martin Scorsese           12
Name: count, dtype: int64

In [ ]:
#Total no. of 'directors'
df["director"].value_counts().sum()

np.int64(5398)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7689 non-null   datetime64[ns]
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 730.2+ KB

In [10]:
df.describe()

                          date_added  release_year
count                           7689   7787.000000
mean   2019-01-07 20:44:06.273897728   2013.932580
min              2008-01-01 00:00:00   1925.000000
25%              2018-02-06 00:00:00   2013.000000
50%              2019-03-15 00:00:00   2017.000000
75%              2020-01-25 00:00:00   2018.000000
max              2021-01-16 00:00:00   2021.000000
std                              NaN      8.757395